name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as gif or svg"
author: "platane"

runs:
  using: docker
  image: docker://platane/snk@sha256:e2cd3268901a65f1402bea9133b8d6ed4a34796ca92ead9686f5aa048f22487a

inputs:
  github_user_name:
    description: "Xchenya"
    required: true
  gif_out_path:
    description: "path of the generated gif file. If left empty, the gif file will not be generated."
    required: false
    default: null
  svg_out_path:
    description: "path of the generated svg file. If left empty, the svg file will not be generated."
    required: false
    default: null

outputs:
  gif_out_path:
    description: "path of the generated gif"
  svg_out_path:
    description: "path of the generated svg"
